pipeline:
  deploy:
    image: alpine:3.7
    commands:
      - echo "deploy"
      - echo $TEST_SECRET
    when:
      event: push
      branch: test
    secrets:
      - source: test_secret
        target: TEST_SECRET
